kind: Deployment
apiVersion: apps/v1
metadata:
  name: lifemanager-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lifemanager-app
      version: v101
  template:
    metadata:
      name: lifemanager-pod
      labels:
        app: lifemanager-app
        version: v101
    spec:
      containers:
        - name: lifemanager-container
          image: lifemanager-image
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              hostPort: 8080
            