apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lifemanager-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: lifemanager.info
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lifemanager-service
            port:
              number: 5052